
FROM node:22-bullseye AS builder

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

WORKDIR /src

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY packages/ ./packages/

COPY apps/ ./apps/

COPY config.sample.json ./config.json

RUN pnpm install --frozen-lockfile

RUN pnpm client:build



FROM nginxinc/nginx-unprivileged:alpine-slim

USER root

RUN apk add jq moreutils

COPY --from=builder /src/apps/blackout-client/dist /app

COPY config.sample.json /app/config.json

COPY deploy/docker/nginx-templates/* /etc/nginx/templates/

COPY deploy/docker/docker-entrypoint.d/* /docker-entrypoint.d/

RUN rm -rf /usr/share/nginx/html && ln -s /app /usr/share/nginx/html

USER nginx

ENV ELEMENT_WEB_PORT=80

HEALTHCHECK --start-period=5s CMD wget -q --spider http://localhost:$ELEMENT_WEB_PORT/health/ready
