import type { Page } from '@playwright/test';
import {
  snapVisual,
  visualTest as test,
} from '../../../apps/blackout-client/tests/e2e/helpers/visual';

/**
 * Authenticated visual regression coverage for the launch-smoke shell.
 *
 * Same gating as the rest of playwright/e2e/launch-smoke/* — needs a live
 * homeserver and seed users. Skipped whenever BLACKOUT_E2E_BASE_URL is
 * unset (CI included) because the vite preview spun up by
 * playwright.config.ts only serves the static client bundle — there is no
 * homeserver to authenticate against, so the signIn flow would always
 * fail. A dedicated authed workflow can opt-in by exporting
 * BLACKOUT_E2E_BASE_URL pointing at a live stack.
 *
 * Selectors are deliberately lenient and mirror messaging.spec.ts /
 * auth.spec.ts so we don't drift apart from the existing launch-smoke
 * harness.
 */

const LS_MEMBER_A_USERNAME =
  process.env.LS_MEMBER_A_USERNAME ?? process.env.LS_AUTH_USERNAME ?? 'smoke_member_a';
const LS_MEMBER_A_PASSWORD =
  process.env.LS_MEMBER_A_PASSWORD ?? process.env.LS_AUTH_PASSWORD ?? 'change-me';

test.beforeEach(async ({}, testInfo) => {
  if (!process.env.BLACKOUT_E2E_BASE_URL) {
    testInfo.skip(true, 'BLACKOUT_E2E_BASE_URL not set — skipping live-stack visual run.');
  }
});

const LS_SMOKE_ROOM = process.env.LS_SMOKE_ROOM ?? 'smoke-launch';

const signIn = async (page: Page): Promise<void> => {
  await page.goto('/');
  if (!/\/login/i.test(page.url())) return;
  await page.getByLabel(/username/i).fill(LS_MEMBER_A_USERNAME);
  await page.getByLabel(/password/i).fill(LS_MEMBER_A_PASSWORD);
  await page.getByRole('button', { name: /sign in|log in/i }).click();
  await page.waitForURL((url) => !/\/login/i.test(url.pathname), { timeout: 20_000 });
};

const openRoom = async (page: Page, roomName: string): Promise<void> => {
  const roomLink = page.getByRole('link', { name: new RegExp(`#?${roomName}`, 'i') }).first();
  if (await roomLink.isVisible().catch(() => false)) {
    await roomLink.click();
  } else {
    await page.goto(`/#/room/%23${roomName}:${new URL(page.url()).host}`);
  }
};

test.describe('Blackout authed visual surfaces', () => {
  test('home after login', async ({ page, visualMeta }) => {
    await signIn(page);
    await snapVisual(page, `home-${visualMeta.viewport}-${visualMeta.theme}`, {
      mask: [
        page.locator('[data-testid$="-timestamp"]'),
        page.locator('[data-testid$="-last-seen"]'),
      ],
    });
  });

  test('settings shell', async ({ page, visualMeta }) => {
    await signIn(page);
    await page.goto('/settings');
    await snapVisual(page, `settings-${visualMeta.viewport}-${visualMeta.theme}`);
  });

  // Regression guard for the Prism→Shiki code-block highlighter swap. Sends a
  // multi-language fenced code block, then snapshots the rendered message so
  // a future change to ReactPrism / Shiki themes is caught as a pixel diff.
  //
  // NOTE: baselines for this test do not exist yet — they must be generated by
  // a maintainer on a machine with Playwright browsers + a live stack via
  // `BLACKOUT_E2E_BASE_URL=... pnpm exec playwright test gif... --update-snapshots`.
  // Until then this test will fail-on-missing-baseline only when the authed
  // visual suite is opted into; it is skipped in normal CI (no BLACKOUT_E2E_BASE_URL).
  test('code block syntax highlighting (Shiki)', async ({ page, visualMeta }) => {
    await signIn(page);
    await openRoom(page, LS_SMOKE_ROOM);

    const composer = page.getByRole('textbox', { name: /message|compose/i }).first();
    const marker = `shiki-visual-${Date.now()}`;
    // Fenced TypeScript block — exercises keyword/type/string/number tokens.
    const code = ['```ts', `// ${marker}`, 'const greet = (n: number): string =>', '  `hi ${n}`;', '```'].join('\n');
    await composer.fill(code);
    await composer.press('Enter');

    const block = page.locator('pre code.shiki-highlighted').last();
    await expect(block).toBeVisible({ timeout: 30_000 });
    await snapVisual(page, `code-block-shiki-${visualMeta.viewport}-${visualMeta.theme}`, {
      mask: [page.locator('[data-testid$="-timestamp"]')],
    });
  });
});
