{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blackout-api
  labels: {{- include "blackout.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    name: blackout-api
    creationPolicy: Owner
  data:
    {{- range $envKey, $remoteKey := .Values.externalSecrets.remoteRefs }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $remoteKey }}
    {{- end }}
{{- end }}
