import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
// @ts-expect-error - plain .mjs release script, deliberately dependency-free so
// it runs on bare node during a release; no types are published for it.
import {
    GRADLE_PATH,
    PBXPROJ_PATH,
    bumpGradle,
    bumpPbxproj,
    hasIosProject,
    parseBuild,
    parseVersion,
    readCurrent,
} from '../scripts/set-version.mjs';

// The real project file, read but never written — this assertion is what
// catches a Capacitor regeneration silently changing the shape the script
// depends on.
const GRADLE: string = readFileSync(GRADLE_PATH, 'utf8');

test('parseVersion accepts MAJOR.MINOR.PATCH and rejects the rest', () => {
    assert.equal(parseVersion('1.2.0'), '1.2.0');
    assert.equal(parseVersion('10.0.11'), '10.0.11');
    for (const bad of ['1.2', '1', 'v1.2.0', '1.2.0-beta', '', null, undefined]) {
        assert.throws(() => parseVersion(bad), /MAJOR\.MINOR\.PATCH/);
    }
});

test('parseBuild accepts positive integers only', () => {
    assert.equal(parseBuild('7'), 7);
    assert.equal(parseBuild(7), 7);
    for (const bad of ['0', '-1', '1.5', 'abc', '', null, undefined]) {
        assert.throws(() => parseBuild(bad));
    }
});

test('readCurrent reads the committed version out of build.gradle', () => {
    const current = readCurrent(GRADLE);
    assert.equal(typeof current.version, 'string');
    assert.equal(typeof current.build, 'number');
    assert.match(current.version, /^\d+\.\d+\.\d+$/);
});

test('bumpGradle rewrites both fields in the real file', () => {
    const out: string = bumpGradle(GRADLE, { version: '2.3.4', build: 12 });
    assert.match(out, /versionName "2\.3\.4"/);
    assert.match(out, /versionCode 12/);
    assert.deepEqual(readCurrent(out), { version: '2.3.4', build: 12 });
    // Nothing else moved: exactly two lines differ.
    const before = GRADLE.split('\n');
    const changed = out.split('\n').filter((line, i) => line !== before[i]);
    assert.equal(changed.length, 2);
});

test('bumpGradle refuses a file that lost its version fields', () => {
    assert.throws(
        () => bumpGradle('android { }', { version: '1.0.0', build: 1 }),
        /expected exactly one versionName and one versionCode/
    );
});

test('bumpPbxproj moves Debug and Release together', () => {
    // Synthetic fixture rather than the real file: ios/App/App.xcodeproj is
    // generated by `pnpm add:ios` on a Mac and is not committed, so there is no
    // real pbxproj here to read. This keeps the rewrite covered anyway, and the
    // shape below is what Capacitor emits.
    const fixture = [
        '\t\t\tbuildSettings = {',
        '\t\t\t\tCURRENT_PROJECT_VERSION = 1;',
        '\t\t\t\tMARKETING_VERSION = 1.0;',
        '\t\t\t};',
        '\t\t\tname = Debug;',
        '\t\t\tbuildSettings = {',
        '\t\t\t\tCURRENT_PROJECT_VERSION = 1;',
        '\t\t\t\tMARKETING_VERSION = 1.0;',
        '\t\t\t};',
        '\t\t\tname = Release;',
    ].join('\n');

    const out: string = bumpPbxproj(fixture, { version: '2.3.4', build: 12 });
    const marketing = [...out.matchAll(/MARKETING_VERSION = ([^;]+);/g)].map((m) => m[1]);
    const project = [...out.matchAll(/CURRENT_PROJECT_VERSION = ([^;]+);/g)].map((m) => m[1]);
    assert.equal(marketing.length, 2, 'expected Debug and Release configs');
    assert.equal(project.length, 2);
    assert.deepEqual(new Set(marketing), new Set(['2.3.4']));
    assert.deepEqual(new Set(project), new Set(['12']));
});

test('bumpPbxproj refuses a file with mismatched version keys', () => {
    assert.throws(
        () => bumpPbxproj('MARKETING_VERSION = 1.0;', { version: '1.0.0', build: 1 }),
        /matching MARKETING_VERSION\/CURRENT_PROJECT_VERSION counts/
    );
});

test('the two platforms agree on version and build, once iOS exists', () => {
    // Today ios/App/App.xcodeproj is not committed, so there is nothing to drift
    // from and this asserts the skip is real rather than silently passing. Once
    // `pnpm add:ios` output lands, the same test starts enforcing parity — a
    // drift means someone edited one project by hand, or fastlane's
    // increment_build_number bumped iOS without committing it (see the script's
    // header and README "Versioning").
    const { version, build } = readCurrent(GRADLE);

    if (!hasIosProject()) {
        assert.equal(
            hasIosProject(PBXPROJ_PATH),
            false,
            'iOS project absent, so parity cannot be checked yet'
        );
        return;
    }

    const pbxproj = readFileSync(PBXPROJ_PATH, 'utf8');
    const marketing = new Set(
        [...pbxproj.matchAll(/MARKETING_VERSION = ([^;]+);/g)].map((m) => m[1])
    );
    const project = new Set(
        [...pbxproj.matchAll(/CURRENT_PROJECT_VERSION = ([^;]+);/g)].map((m) => m[1])
    );
    assert.deepEqual(marketing, new Set([version]), 'iOS marketing version drift');
    assert.deepEqual(project, new Set([String(build)]), 'iOS build number drift');
});
