/**
 * Pure docker-compose template generator for the per-canopy
 * self-host blueprint described in master-plan §18. Mirrors the
 * existing `infra/docker-compose.yml` but parametrized so a canopy
 * admin can download a working stack with their own domain, admin
 * email, and tenant id baked in. No matrix-js-sdk imports — this
 * module stays test-friendly and registry-load-safe.
 */

export interface SelfHostInput {
    /**
     * Canopy id this stack hosts (used for labels + the docker
     * project name). Lowercased + hyphenated.
     */
    canopyId: string;
    /** Public domain admins will run this stack at, e.g. `example.coop`. */
    domain: string;
    /** Admin email used by Synapse + Owncast for owner-of-record. */
    adminEmail: string;
    /**
     * Optional federation tier. Drives whether the generated
     * `homeserver.yaml` enables federation outbound by default.
     */
    federationTier?: 'local' | 'zone' | 'global';
    /** When false, omits the Owncast service from the compose. */
    includeOwncast?: boolean;
}

const slug = (value: string): string =>
    value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');

export interface ValidationResult {
    valid: boolean;
    errors: string[];
}

const DOMAIN_PATTERN = /^[a-z0-9.-]+$/i;
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const validateSelfHostInput = (input: SelfHostInput): ValidationResult => {
    const errors: string[] = [];
    if (!slug(input.canopyId)) errors.push('canopyId is required');
    if (!input.domain || !DOMAIN_PATTERN.test(input.domain)) {
        errors.push('domain must be a valid hostname');
    }
    if (!input.adminEmail || !EMAIL_PATTERN.test(input.adminEmail)) {
        errors.push('adminEmail must be a valid email address');
    }
    return { valid: errors.length === 0, errors };
};

/**
 * Builds the docker-compose YAML body. Returned as a string so the
 * UI can stuff it straight into a Blob for download. Tests assert on
 * the well-formed shape rather than running the compose itself.
 */
export const buildSelfHostCompose = (input: SelfHostInput): string => {
    const validation = validateSelfHostInput(input);
    if (!validation.valid) {
        throw new Error(`Invalid self-host input: ${validation.errors.join(', ')}`);
    }
    const project = slug(input.canopyId);
    const tier = input.federationTier ?? 'global';
    const owncast = input.includeOwncast ?? true;

    const lines: string[] = [];
    lines.push('# Generated by Blackout self-host wizard. Do not edit by hand.');
    lines.push(`# Canopy: ${input.canopyId}`);
    lines.push(`# Domain: ${input.domain}`);
    lines.push(`# Admin: ${input.adminEmail}`);
    lines.push(`# Federation tier: ${tier}`);
    lines.push('version: "3.9"');
    lines.push(`name: blackout-${project}`);
    lines.push('services:');
    lines.push('  postgres:');
    lines.push('    image: postgres:15');
    lines.push('    environment:');
    lines.push('      POSTGRES_USER: synapse');
    lines.push('      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}');
    lines.push('      POSTGRES_DB: synapse');
    lines.push('    volumes:');
    lines.push('      - postgres-data:/var/lib/postgresql/data');
    lines.push('    restart: unless-stopped');
    lines.push('  synapse:');
    lines.push('    image: matrixdotorg/synapse:latest');
    lines.push('    environment:');
    lines.push(`      SYNAPSE_SERVER_NAME: ${input.domain}`);
    lines.push(`      SYNAPSE_REPORT_STATS: "no"`);
    lines.push(`      SYNAPSE_FEDERATION: "${tier === 'local' ? 'no' : 'yes'}"`);
    lines.push(`      ADMIN_EMAIL: ${input.adminEmail}`);
    lines.push('    depends_on: [postgres]');
    lines.push('    volumes:');
    lines.push('      - synapse-data:/data');
    lines.push('    restart: unless-stopped');
    lines.push('  matrix-media-repo:');
    lines.push('    image: turt2live/matrix-media-repo:latest');
    lines.push('    depends_on: [postgres]');
    lines.push('    volumes:');
    lines.push('      - media-data:/data');
    lines.push('    restart: unless-stopped');
    if (owncast) {
        lines.push('  owncast:');
        lines.push('    image: gabekangas/owncast:latest');
        lines.push('    ports:');
        lines.push('      - "1935:1935"');
        lines.push('      - "8080:8080"');
        lines.push('    volumes:');
        lines.push('      - owncast-data:/app/data');
        lines.push('    restart: unless-stopped');
    }
    lines.push('volumes:');
    lines.push('  postgres-data:');
    lines.push('  synapse-data:');
    lines.push('  media-data:');
    if (owncast) lines.push('  owncast-data:');
    return `${lines.join('\n')}\n`;
};

/**
 * Filename hint surfaced to the download <a> element. Stays in this
 * module so the wizard component doesn't repeat the slug logic.
 */
export const buildSelfHostFilename = (canopyId: string): string =>
    `docker-compose.${slug(canopyId) || 'canopy'}.yml`;
