export type BlackoutEventName =
    | 'blackout.governance.proposal.created'
    | 'blackout.governance.vote.cast'
    | 'blackout.governance.meeting.scheduled'
    | 'blackout.governance.treasury.snapshot.published'
    | 'blackout.forum.post.created'
    | 'blackout.deaddrop.created'
    | 'blackout.deaddrop.opened'
    | 'blackout.moderation.action.taken'
    | 'blackout.notifications.digest.generated'
    | 'blackout.notifications.digest.acknowledged'
    | 'blackout.media.upload.completed'
    | 'blackout.call.launch.intent'
    | 'blackout.stego.channel.created'
    | 'blackout.stego.channel.rotated'
    | 'blackout.stego.channel.expired'
    | 'blackout.settings.changed'
    | 'blackout.settings.labs.gate.changed'
    | 'blackout.moderation.mjolnir.protection.changed'
    | 'blackout.moderation.mjolnir.banlist.changed'
    | 'blackout.federation.alert.status'
    | 'blackout.townhall.lifecycle'
    | 'blackout.revenue.ops.snapshot'
    | 'blackout.thread.activity.updated'
    | 'blackout.auth.session.continued'
    | 'blackout.education.module.progress'
    | 'blackout.deaddrop.mutual-aid.thread.opened'
    | 'blackout.deaddrop.mutual-aid.thread.updated'
    | 'blackout.deadman.switch.armed'
    | 'blackout.deadman.switch.checked_in'
    | 'blackout.deadman.switch.grace'
    | 'blackout.deadman.switch.triggered'
    | 'blackout.deadman.switch.cancelled'
    | 'blackout.deaddrop.share.submitted'
    | 'blackout.deaddrop.audit'
    | 'blackout.den.playbook.set'
    | 'blackout.governance.round.opened'
    | 'blackout.governance.round.closed'
    | 'blackout.governance.role.set'
    | 'blackout.den.composted'
    | 'blackout.den.document.upserted'
    | 'blackout.user.quests'
    | 'blackout.user.sheet.sharing';

export type EventEnvelope<TName extends BlackoutEventName, TPayload> = {
    event: TName;
    roomId: string;
    senderId: string;
    occurredAt: string;
    payload: TPayload;
};
