export const schema = {
  users: 'users',
  communities: 'communities',
  channels: 'channels',
  messages: 'messages',
  votes: 'votes',
  voteEntries: 'vote_entries',
  disputes: 'disputes',
  federationLinks: 'federation_links',
  reputationEvents: 'reputation_events',
  subscriptions: 'subscriptions',
  marketplaceListingsCache: 'marketplace_listings_cache',
  marketplaceEntitlements: 'marketplace_entitlements',
  marketplaceWebhookEvents: 'marketplace_webhook_events',
  marketplaceSellerProfiles: 'marketplace_seller_profiles',
  marketplaceLicenseKeys: 'marketplace_license_keys',
  marketplaceProviderConfig: 'marketplace_provider_config',
} as const;
